name: Deploy no GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-dev
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/estudo_cloud_run_ci:latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v0.1.1
      with:
        service_account_key: ${{secrets.GCP_CREDENTIALS}}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
      
    - name: configure Docker
      run: gcloud auth configure-docker --quiet

    - name: build image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/estudo_cloud_run_ci .

    - name: push image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/estudo_cloud_run_ci

    - name: deploy
      run: gcloud run deploy estudo-cloud-run --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/estudo_cloud_run_ci
